server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location ^~ /manager/ {
        try_files $uri $uri/ /manager/index.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}