# Production upstream configuration
upstream django_app {
    server web:8000;
    keepalive 32;
}

upstream bookshelf_app {
    server app1:6001;
    keepalive 32;
}

upstream backend_api {
    server backend_api:5000;
    keepalive 32;
}