# Generated by Django 5.1.7 on 2025-11-20 00:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('tenancy_agreement_id', models.IntegerField(blank=True, db_column='TenancyAgreementId', null=True)),
                ('tenant_id', models.CharField(db_column='TenantId', max_length=150)),
                ('unit_id', models.IntegerField(blank=True, db_column='UnitId', null=True)),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(blank=True, db_column='CreatedAt', null=True)),
                ('channel', models.CharField(blank=True, db_column='Channel', max_length=100, null=True)),
                ('reference', models.CharField(blank=True, db_column='Reference', max_length=250, null=True)),
                ('provider', models.IntegerField(blank=True, db_column='Provider', null=True)),
                ('status', models.IntegerField(blank=True, db_column='Status', null=True)),
                ('email', models.EmailField(blank=True, db_column='Email', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=20, null=True)),
                ('currency', models.CharField(blank=True, db_column='Currency', max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'Payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=250)),
                ('location', models.CharField(blank=True, db_column='Location', max_length=512, null=True)),
                ('image_url', models.CharField(blank=True, db_column='ImageUrl', max_length=500, null=True)),
                ('no_of_units', models.IntegerField(blank=True, db_column='NoOfUnits', null=True)),
                ('no_of_floors', models.IntegerField(blank=True, db_column='NoOfFloors', null=True)),
                ('availability', models.IntegerField(blank=True, db_column='Availability', null=True)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'db_table': 'Properties',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tenancy',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('unit_id', models.IntegerField(db_column='UnitId')),
                ('tenant_id', models.CharField(db_column='TenantId', max_length=150)),
                ('property_id', models.IntegerField(db_column='PropertyId')),
                ('contract_start_date', models.DateTimeField(blank=True, db_column='ContractStartDate', null=True)),
                ('contract_end_date', models.DateTimeField(blank=True, db_column='ContractEndDate', null=True)),
                ('contract_duration_months', models.IntegerField(blank=True, db_column='ContractDurationMonths', null=True)),
                ('total_amount_paid', models.DecimalField(blank=True, db_column='TotalAmountPaid', decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'verbose_name': 'Tenancy Agreement',
                'verbose_name_plural': 'Tenancy Agreements',
                'db_table': 'TenancyAgreements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=150)),
                ('first_name', models.CharField(db_column='FirstName', max_length=150)),
                ('last_name', models.CharField(db_column='LastName', max_length=150)),
                ('email', models.EmailField(db_column='Email', max_length=254)),
                ('password_hash', models.CharField(db_column='PasswordHash', max_length=512)),
                ('role', models.CharField(db_column='Role', default='Tenant', max_length=50)),
                ('refresh_token', models.CharField(blank=True, db_column='RefreshToken', max_length=512, null=True)),
                ('refresh_token_expiry_time', models.DateTimeField(blank=True, db_column='RefreshTokenExpiryTime', null=True)),
                ('created_at', models.DateTimeField(db_column='CreatedAt', default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, db_column='UpdatedAt', null=True)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'db_table': 'Users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('property_id', models.IntegerField(db_column='PropertyId')),
                ('room_number', models.CharField(db_column='RoomNumber', max_length=50)),
                ('cost', models.DecimalField(db_column='Cost', decimal_places=2, max_digits=12)),
                ('availability', models.IntegerField(db_column='Availability', default=1)),
                ('floor', models.IntegerField(blank=True, db_column='Floor', null=True)),
                ('image_url', models.CharField(blank=True, db_column='ImageUrl', max_length=500, null=True)),
                ('max_no_of_people', models.IntegerField(blank=True, db_column='MaxNoOfPeople', null=True)),
                ('unit_type', models.IntegerField(blank=True, db_column='UnitType', null=True)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'db_table': 'Units',
                'managed': False,
            },
        ),
    ]
